#!/bin/bash
# ====================================================================
#  Mailcow Zabbix Monitoring - Installer
#  Version:    1.0
#  Vendor:     Alexander Fox | PlaNet Fox
#  Project:    https://github.com/linuser/Mailcow-Zabbix-Monitoring
#  Description: Installs Collector, Reader, Configs and systemd Units
#  License:    GPLv3 (see LICENSE)
#  Created with Open Source and ♥
# ====================================================================
set -e

RED='\033[0;31m'; GREEN='\033[0;32m'; BLUE='\033[0;34m'; YELLOW='\033[1;33m'; NC='\033[0m'

echo ""
echo -e "${BLUE}╔══════════════════════════════════════════╗${NC}"
echo -e "${BLUE}║  Mailcow Monitoring v1.0 - Install       ║${NC}"
echo -e "${BLUE}║  Secure Service Architecture             ║${NC}"
echo -e "${BLUE}╚══════════════════════════════════════════╝${NC}"
echo ""

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"

# --- Root check ---
if [ "$EUID" -ne 0 ]; then
    echo -e "${RED}Please run as root${NC}"
    exit 1
fi

# --- Dependency check ---
MISSING_REQUIRED=()
MISSING_OPTIONAL=()
for cmd in python3 docker zabbix_get; do
    command -v "$cmd" &>/dev/null || MISSING_REQUIRED+=("$cmd")
done
for cmd in dig openssl nc pflogsumm jq; do
    command -v "$cmd" &>/dev/null || MISSING_OPTIONAL+=("$cmd")
done
if [ ${#MISSING_REQUIRED[@]} -gt 0 ]; then
    echo -e "${RED}ERROR: Missing required dependencies: ${MISSING_REQUIRED[*]}${NC}"
    exit 1
fi
if [ ${#MISSING_OPTIONAL[@]} -gt 0 ]; then
    echo -e "${YELLOW}⚠ Optional dependencies not found: ${MISSING_OPTIONAL[*]}${NC}"
    echo -e "${YELLOW}  Some monitoring checks may be unavailable.${NC}"
fi

# --- Find Mailcow ---
# Priority: argument > environment variable > existing config > auto-detect
if [ -n "$1" ] && [ -f "$1/mailcow.conf" ]; then
    MAILCOW_DIR="$1"
elif [ -n "$MAILCOW_DIR" ] && [ -f "$MAILCOW_DIR/mailcow.conf" ]; then
    : # use MAILCOW_DIR from environment
elif [ -f /etc/mailcow-monitor.conf ]; then
    MAILCOW_DIR=$(grep -oP '^MAILCOW_DIR=\K[^#]+' /etc/mailcow-monitor.conf | tr -d '"' | tr -d "'" | xargs)
fi

# Auto-detect known paths
if [ -z "$MAILCOW_DIR" ] || [ ! -f "$MAILCOW_DIR/mailcow.conf" ]; then
    for TRY_DIR in /opt/mailcow-dockerized /opt/containers/mailcow /srv/mailcow-dockerized /home/mailcow-dockerized; do
        if [ -f "$TRY_DIR/mailcow.conf" ]; then
            MAILCOW_DIR="$TRY_DIR"
            break
        fi
    done
fi

if [ -z "$MAILCOW_DIR" ] || [ ! -f "$MAILCOW_DIR/mailcow.conf" ]; then
    echo -e "${RED}mailcow.conf not found. Options:${NC}"
    echo -e "${YELLOW}  sudo ./install.sh /path/to/mailcow${NC}"
    echo -e "${YELLOW}  sudo MAILCOW_DIR=/path/to/mailcow ./install.sh${NC}"
    exit 1
fi

echo -e "${GREEN}✓ Mailcow found at: $MAILCOW_DIR${NC}"

DOMAIN=$(grep -oP "^MAILCOW_HOSTNAME=\K[a-zA-Z0-9._-]+" "$MAILCOW_DIR/mailcow.conf" 2>/dev/null)
echo -e "${GREEN}✓ Domain: $DOMAIN${NC}"

# --- Write central monitor config ---
cat > /etc/mailcow-monitor.conf <<EOF
# Mailcow Zabbix Monitoring - central configuration
# Generated by install.sh on $(date)
MAILCOW_DIR="$MAILCOW_DIR"

# Optional: override backup directory (leave empty to auto-detect /opt/backup or /backup)
BACKUP_PATH="$BACKUP_PATH"

# Set to true to skip git fetch during version checks (useful on air-gapped servers)
SKIP_GIT_FETCH="false"
EOF
chmod 644 /etc/mailcow-monitor.conf
echo -e "${GREEN}✓ /etc/mailcow-monitor.conf written (MAILCOW_DIR=$MAILCOW_DIR)${NC}"

# --- Backup path ---
BACKUP_PATH="/opt/backup"
OLD_BACKUP=$(grep -rh "BACKUP_PATH_PLACEHOLDER\|find -L " /usr/local/bin/check_backup_*.sh 2>/dev/null | grep -oP '(?<=-L )[^ ]+' | head -1)
[ -n "$OLD_BACKUP" ] && BACKUP_PATH="$OLD_BACKUP"
if [ -d "/opt/backup" ]; then BACKUP_PATH="/opt/backup"
elif [ -d "/backup" ]; then BACKUP_PATH="/backup"
fi
echo -e "${GREEN}✓ Backup path: $BACKUP_PATH${NC}"

# ====================================================================
echo ""
echo -e "${BLUE}=== [1/5] Installing scripts ===${NC}"
# ====================================================================

# Common library + Reader
for SCRIPT in mailcow-common.sh mailcow-reader.sh; do
    cp "$SCRIPT_DIR/scripts/$SCRIPT" /usr/local/bin/
    chmod +x /usr/local/bin/$SCRIPT
    echo -e "  ${GREEN}✓ $SCRIPT${NC}"
done

# Python Collector
cp "$SCRIPT_DIR/scripts/mailcow-collector.py" /usr/local/bin/
chmod +x /usr/local/bin/mailcow-collector.py
echo -e "  ${GREEN}✓ mailcow-collector.py (Python)${NC}"

# Remove old Bash collector
rm -f /usr/local/bin/mailcow-collector.sh
echo -e "  ${GREEN}✓ mailcow-collector.sh (Bash) removed${NC}"

# Clean up old scripts from v4.0-v4.3
for OLD_SCRIPT in check_postfix_running.sh check_backup_age.sh check_backup_size.sh \
                  check_backup_count.sh check_backup_exists.sh check_backup_zero.sh \
                  check_dovecot_running.sh check_rspamd_running.sh check_fail2ban.sh \
                  check_disk_usage.sh check_vmail.sh mailcow_version.sh; do
    if [ -f "/usr/local/bin/$OLD_SCRIPT" ]; then
        rm -f "/usr/local/bin/$OLD_SCRIPT"
        echo -e "  ${YELLOW}✓ $OLD_SCRIPT (outdated) removed${NC}"
    fi
done

# Delete old slow cache (format has changed)
rm -f /var/tmp/mailcow-monitor-slow.json
echo -e "  ${GREEN}✓ Slow cache reset${NC}"

# Update existing scripts
for SCRIPT in check_rbl.sh check_dns.sh check_tls.sh check_ptr.sh check_open_relay.sh \
              check_security_audit.sh \
              dovecot_check.sh sync_jobs_check.sh \
              postfix_stats_docker.sh postfix_log_analysis.sh; do
    if [ -f "$SCRIPT_DIR/scripts/$SCRIPT" ]; then
        cp "$SCRIPT_DIR/scripts/$SCRIPT" /usr/local/bin/
        chmod +x /usr/local/bin/$SCRIPT
        echo -e "  ${GREEN}✓ $SCRIPT${NC}"
    fi
done

# Python Collector auto-detects backup path

# Git safe.directory
git config --system --add safe.directory "$MAILCOW_DIR" 2>/dev/null

# pflogsumm for mailflow statistics
if ! which pflogsumm >/dev/null 2>&1; then
    echo -e "  ${YELLOW}pflogsumm not found, installing...${NC}"
    apt-get install -y pflogsumm >/dev/null 2>&1 && \
        echo -e "  ${GREEN}✓ pflogsumm installed${NC}" || \
        echo -e "  ${YELLOW}⚠ pflogsumm could not be installed (mailflow stats unavailable)${NC}"
else
    echo -e "  ${GREEN}✓ pflogsumm present${NC}"
fi

# ====================================================================
echo ""
echo -e "${BLUE}=== [2/5] Installing systemd service ===${NC}"
# ====================================================================

cp "$SCRIPT_DIR/mailcow-monitor.service" /etc/systemd/system/
cp "$SCRIPT_DIR/mailcow-monitor.timer" /etc/systemd/system/
systemctl daemon-reload
systemctl enable mailcow-monitor.timer
systemctl start mailcow-monitor.timer
echo -e "${GREEN}✓ mailcow-monitor.timer enabled${NC}"

# Start first run manually
echo -e "${YELLOW}  First collector run (may take up to 60s)...${NC}"
systemctl start mailcow-monitor.service
echo -e "${GREEN}✓ First run complete${NC}"

# ====================================================================
echo ""
echo -e "${BLUE}=== [3/5] Configuring Zabbix Agent ===${NC}"
# ====================================================================

# Remove old individual configs
rm -f /etc/zabbix/zabbix_agent2.d/mailcow-*.conf
rm -f /etc/zabbix/zabbix_agent2.d/mailcow.conf.bak

# New single config
cp "$SCRIPT_DIR/mailcow-zabbix.conf" /etc/zabbix/zabbix_agent2.d/mailcow.conf
echo -e "${GREEN}✓ 307 UserParameters in one config${NC}"

# UnsafeUserParameters no longer needed
if grep -q "^UnsafeUserParameters=1" /etc/zabbix/zabbix_agent2.conf 2>/dev/null; then
    sed -i 's/^UnsafeUserParameters=1/UnsafeUserParameters=0/' /etc/zabbix/zabbix_agent2.conf
    echo -e "${GREEN}✓ UnsafeUserParameters=0 set${NC}"
fi

# ====================================================================
echo ""
echo -e "${BLUE}=== [4/5] Hardening security ===${NC}"
# ====================================================================

# Docker group: do not touch (may be needed by other templates)

# Remove old sudoers
if [ -f /etc/sudoers.d/zabbix-mailcow ]; then
    rm -f /etc/sudoers.d/zabbix-mailcow
    echo -e "${GREEN}✓ Sudo rules removed${NC}"
else
    echo -e "${GREEN}✓ No sudo rules present${NC}"
fi

# Make JSON file readable for zabbix
chmod 644 /var/tmp/mailcow-monitor.json 2>/dev/null

# ====================================================================
echo ""
echo -e "${BLUE}=== [5/5] Restarting agent + test ===${NC}"
# ====================================================================

systemctl restart zabbix-agent2
sleep 3

# Quick test
ERRORS=0
PASS=0
for key in postfix.process.running mailcow.rspamd.scanned mailcow.disk.root.used \
           mailcow.dovecot.running mailcow.version.current \
           mailcow.mailbox.total mailcow.collector.running; do
    RESULT=$(zabbix_get -s 127.0.0.1 -k "$key" 2>&1) || true
    if echo "$RESULT" | grep -q "Connection reset by peer"; then
        echo -e "  ${RED}✗ Agent rejected connection from 127.0.0.1${NC}"
        echo -e "  ${YELLOW}  → Add 127.0.0.1 to Server= in your Zabbix agent config and restart zabbix-agent2${NC}"
        ERRORS=$((ERRORS + 1))
        break
    elif [ -n "$RESULT" ] && ! echo "$RESULT" | grep -q "NOTSUPPORTED\|error"; then
        echo -e "  ${GREEN}✓ $key = $RESULT${NC}"
        PASS=$((PASS + 1))
    else
        echo -e "  ${RED}✗ $key = $RESULT${NC}"
        ERRORS=$((ERRORS + 1))
    fi
done

echo ""
echo -e "${BLUE}╔══════════════════════════════════════════╗${NC}"
echo -e "${BLUE}║        INSTALLATION COMPLETE             ║${NC}"
echo -e "${BLUE}╚══════════════════════════════════════════╝${NC}"
echo ""
echo -e "  ${GREEN}✓ Collector: systemd timer (every 60s as root)${NC}"
echo -e "  ${GREEN}✓ Reader: /var/tmp/mailcow-monitor.json${NC}"
echo -e "  ${GREEN}✓ Zabbix: reads JSON only (no privileges required)${NC}"
echo ""
echo -e "  Security:"
echo -e "  ${GREEN}✓ No UnsafeUserParameters${NC}"

echo -e "  ${GREEN}✓ No sudo for Zabbix${NC}"
echo ""
echo -e "  Test: $PASS passed, $ERRORS failed"
echo ""
echo -e "  Commands:"
echo -e "    systemctl status mailcow-monitor.timer"
echo -e "    cat /var/tmp/mailcow-monitor.json | python3 -m json.tool | head -20"
echo -e "    zabbix_get -s 127.0.0.1 -k mailcow.rspamd.scanned"
echo ""
echo -e "  ${YELLOW}⚠ Zabbix Template:${NC}"
echo -e "    If old individual templates (Postfix, Dovecot, Security...)"
echo -e "    are still linked: Unlink + import 'Mailcow Complete Monitoring v1.0'"
echo -e "    Template: templates/mailcow-complete-monitoring.yaml"
